config/routes.rb
class ActionDispatch::Routing::Mapper
  def draw(routes_name)
    instance_eval(File.read(Rails.root.join("config/routes", "#{@scope[:shallow_prefix]}", "#{routes_name}.rb")))
  end
end

Rails.application.routes.draw do
  devise_for :admins, :path => 'admin', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, controllers: { sessions: "admin/sessions", passwords: "admin/passwords" }
  devise_for :users

  root 'home#index'

  namespace :admin do
    draw :routes
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :username, uniqueness: { case_sensitive: false }

  attr_accessor :login

  devise :database_authenticatable, :rememberable, :trackable, :validatable, :authentication_keys => [:login]

  def login=(login)
   @login = login
  end

  def login
    @login || self.username || self.email
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => login.downcase }]).first
    else
      where(conditions).first
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ActionController::Base
  layout 'admin'

  before_action :configure_permitted_parameters, if: :devise_controller?

  before_filter :authenticate_admin!

    protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.for(:sign_in) { |a| a.permit(:login, :username, :email, :password, :remember_me) }
    end
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < Admin::BaseController
  def index
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  respond_to :html, :json
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  def index
    @products = Product.all
    respond_with(@products)
  end

  def show
    respond_with(@product)
  end

  def new
    @product = Product.new
    respond_with(@product)
  end

  def edit
  end

  def create
    @product = Product.new(product_params)
    @product.save
    respond_with(@product)
  end

  def update
    @product.update(product_params)
    respond_with(@product)
  end

  def destroy
    @product.destroy
    respond_with(@product)
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :description, :price, :status)
    end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Devise::SessionsController
  layout 'admin_login'
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/admin/dashboard_helper.rb
module Admin::DashboardHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title(page_title)
    content_for :title, "#{I18n.t('administration')} #{" :: #{I18n.t(page_title.to_s)}" unless page_title.nil?}"
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/dashboard/index.html.haml
- title 'dashboard'
= 'in dashboard'

app/views/admin/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.check_box :status %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/admin/products/index.html.erb
<h1>Listing products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.price %></td>
        <td><%= product.status %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @product.status %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/admin/shared/_header.html.haml
%header.header.black-bg
  %div.sidebar-toggle-box
    %div.fa.fa-bars.tooltips{"data-placement" => "right", "data-original-title" =>"Toggle Navigation"}
  = link_to "<b>GORODKNIG ADMIN</b>".html_safe, admin_path, class: "logo"
  %div.nav.notify-row#top_menu
    %ul.nav.top-menu
      %li.dropdown
        =link_to '#' do
          %i.fa.fa-tasks
          %span.badge.bg-theme 4

app/views/home/index.html.haml
%p In Home#index action

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : t('administration')
    = csrf_meta_tags
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if gt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
      = javascript_include_tag "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
    = stylesheet_link_tag "admin", :media => "all"
  %body
    %section#container
      = render "admin/shared/header"
      %div#user_nav{ :style => "padding-top: 80px;" }
        - if admin_signed_in?
          = "Signed in as #{current_admin.email}. Not you? #{link_to 'Sign out', destroy_admin_session_path, method: :delete}".html_safe
      = yield
    = javascript_include_tag "admin"
    = render "shared/notice"

app/views/layouts/admin_login.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : t('gorodknig_admin')
    = csrf_meta_tags
    / HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries
    /[if gt IE 9]
      = javascript_include_tag "https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"
      =javascript_include_tag "https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"
    = stylesheet_link_tag "admin", :media => "all"
  %body
    /  = bootstrap_flash
    = yield
    = javascript_include_tag "admin"
    = render "shared/notice"
    :javascript
      $(document).ready( function() {
        $.backstretch('#{asset_path('admin/login-bg.jpg')}', {speed: 500});
      });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Gorodknig</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shared/_notice.html.haml
- flash.each do |name, msg|
  - name = :error if name.to_sym == :alert
  - title = name.to_s
  - if msg.is_a?(Array)
    - msg.each do |m|
      = js add_gritter(m, image: name, title: I18n.t(title)) unless name == :timedout
  - else
    = js add_gritter(msg, image: name, title: I18n.t(title)) unless name == :timedout
- if defined?(resource) && resource.errors.any? && %w(passwords registrations sessions confirmations).include?(controller_name)
  - resource.errors.full_messages.each do |error|
    = js add_gritter(error, image: :error)